name = "plainenglish/mdbook_luau"
version = "0.1.0"
description = "Framework for writing mdBook preprocessors and renderers with Lune."
authors = ["plainenglish"]
repository = "https://github.com/plainenglishh/mdbook.luau"
license = "MIT"
includes = [
    "pesde.toml",
    "README.md",
    "LICENSE",
    "src/**",
]

[target]
lib = "src/init.luau"
environment = "lune"

[indices]
default = "https://github.com/pesde-pkg/index"
